version: "3.4"
services:
  web:
    build:
      context: .
      target: dev
    image: temp_compose
    container_name: temp_compose_build
    volumes:
      - "./src:/home/app/src"
      - "./index.js:/home/app/index.js"
    environment:
      NODE_ENV: "development"
      S3_ENDPOINT: "http://localstack:4572"
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      API_GATEWAY_ENDPOINT: "http://localstack:4567"
    ports:
      - "3000:3000"
      - "5858:5858"
    